import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
 
const green=Color(0xFF087A3D), darkGreen=Color(0xFF00563E), paleGreen=Color(0xFFEAF8EE);
void main() async { WidgetsFlutterBinding.ensureInitialized(); await Store.i.load(); runApp(const App()); }
 
class User {
  String user,name,role,hash,photo;
  User(this.user,this.name,this.role,this.hash,{this.photo=''});
  Map<String,dynamic> json()=>{'user':user,'name':name,'role':role,'hash':hash,'photo':photo};
  factory User.from(Map<String,dynamic> j)=>User(j['user']??'',j['name']??'',j['role']??'',j['hash']??'',photo:j['photo']??'');
}
class Occ {
  String id,date,time,farm='',plot='',operation='',employee='',role='',type='',body='',desc='',animal='',hospital='',status='Em análise';
  List<String> attendance=[],causes=[],photos=[]; double lat=0,lng=0,accuracy=0;
  Occ(this.id,this.date,this.time);
  Map<String,dynamic> json()=>{'id':id,'date':date,'time':time,'farm':farm,'plot':plot,'operation':operation,'employee':employee,'role':role,'type':type,'body':body,'desc':desc,'animal':animal,'hospital':hospital,'status':status,'attendance':attendance,'causes':causes,'photos':photos,'lat':lat,'lng':lng,'accuracy':accuracy};
  factory Occ.from(Map<String,dynamic> j){final o=Occ(j['id']??'',j['date']??'',j['time']??'');o.farm=j['farm']??'';o.plot=j['plot']??'';o.operation=j['operation']??'';o.employee=j['employee']??'';o.role=j['role']??'';o.type=j['type']??'';o.body=j['body']??'';o.desc=j['desc']??'';o.animal=j['animal']??'';o.hospital=j['hospital']??'';o.status=j['status']??'Em análise';o.attendance=List<String>.from(j['attendance']??[]);o.causes=List<String>.from(j['causes']??[]);o.photos=List<String>.from(j['photos']??[]);o.lat=(j['lat']??0).toDouble();o.lng=(j['lng']??0).toDouble();o.accuracy=(j['accuracy']??0).toDouble();return o;}
}
class Report {String id,title,text;Report(this.id,this.title,this.text);Map<String,dynamic> json()=>{'id':id,'title':title,'text':text};factory Report.from(Map<String,dynamic> j)=>Report(j['id'],j['title'],j['text']);}
 
class Store extends ChangeNotifier {
  Store._(); static final i=Store._(); List<User> users=[];List<Occ> occ=[];List<Report> reports=[];User? current;
  String h(String s)=>sha256.convert(utf8.encode(s)).toString();
  Future<void> load()async{final p=await SharedPreferences.getInstance();users=(jsonDecode(p.getString('users')??'[]')as List).map((e)=>User.from(Map<String,dynamic>.from(e))).toList();occ=(jsonDecode(p.getString('occ')??'[]')as List).map((e)=>Occ.from(Map<String,dynamic>.from(e))).toList();reports=(jsonDecode(p.getString('reports')??'[]')as List).map((e)=>Report.from(Map<String,dynamic>.from(e))).toList();final u=p.getString('logged');for(final x in users){if(x.user==u)current=x;}}
  Future<void> save()async{final p=await SharedPreferences.getInstance();await p.setString('users',jsonEncode(users.map((e)=>e.json()).toList()));await p.setString('occ',jsonEncode(occ.map((e)=>e.json()).toList()));await p.setString('reports',jsonEncode(reports.map((e)=>e.json()).toList()));if(current==null)await p.remove('logged');else await p.setString('logged',current!.user);notifyListeners();}
  Future<String?> register(String u,String pw,String n,String r)async{if(u.trim().isEmpty||n.trim().isEmpty||pw.length<4)return'Preencha os campos. A senha deve ter 4 caracteres ou mais.';if(users.any((x)=>x.user.toLowerCase()==u.trim().toLowerCase()))return'Usuário já existe.';users.add(User(u.trim(),n.trim(),r.trim(),h(pw)));await save();return null;}
  Future<bool> login(String u,String pw)async{for(final x in users){if(x.user.toLowerCase()==u.trim().toLowerCase()&&x.hash==h(pw)){current=x;await save();return true;}}return false;}
  Future<void> logout()async{current=null;await save();}
}
 
// ===== Lista de colaboradores (salva no aparelho) =====
class ColabStore{
  static Future<List<String>> list()async{final p=await SharedPreferences.getInstance();final l=List<String>.from(p.getStringList('colaboradores')??[]);l.sort((a,b)=>a.toLowerCase().compareTo(b.toLowerCase()));return l;}
  static Future<void> add(String n)async{final v=n.trim();if(v.isEmpty)return;final p=await SharedPreferences.getInstance();final l=List<String>.from(p.getStringList('colaboradores')??[]);if(!l.any((e)=>e.toLowerCase()==v.toLowerCase())){l.add(v);await p.setStringList('colaboradores',l);}}
  static Future<void> remove(String n)async{final p=await SharedPreferences.getInstance();final l=List<String>.from(p.getStringList('colaboradores')??[]);l.remove(n);await p.setStringList('colaboradores',l);}
}
class CampoColab extends StatefulWidget{
  final TextEditingController controller;
  const CampoColab({super.key,required this.controller});
  @override State<CampoColab> createState()=>_CampoColabState();
}
class _CampoColabState extends State<CampoColab>{
  final focus=FocusNode();
  List<String> nomes=[];
  @override void initState(){super.initState();carregar();focus.addListener((){if(focus.hasFocus)carregar();});}
  @override void dispose(){focus.dispose();super.dispose();}
  Future<void> carregar()async{final l=await ColabStore.list();if(mounted)setState(()=>nomes=l);}
  @override Widget build(BuildContext context)=>RawAutocomplete<String>(
    textEditingController:widget.controller,
    focusNode:focus,
    optionsBuilder:(v){return v.text.isEmpty?nomes:nomes.where((n)=>n.toLowerCase().contains(v.text.toLowerCase()));},
    fieldViewBuilder:(context,c,f,s)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,focusNode:f,textCapitalization:TextCapitalization.words,decoration:const InputDecoration(labelText:'Funcionário envolvido',suffixIcon:Icon(Icons.arrow_drop_down)))),
    optionsViewBuilder:(context,onSelected,options)=>Align(alignment:Alignment.topLeft,child:Material(elevation:4,borderRadius:BorderRadius.circular(12),child:ConstrainedBox(constraints:const BoxConstraints(maxHeight:220,maxWidth:340),child:ListView(padding:EdgeInsets.zero,shrinkWrap:true,children:options.map((n)=>ListTile(dense:true,title:Text(n),trailing:IconButton(tooltip:'Remover da lista',icon:const Icon(Icons.close,size:18),onPressed:()async{await ColabStore.remove(n);await carregar();}),onTap:()=>onSelected(n))).toList())))),
  );
}
 
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Safe Forest',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:green),scaffoldBackgroundColor:const Color(0xFFF7F7F7),appBarTheme:const AppBarTheme(backgroundColor:darkGreen,foregroundColor:Colors.white),inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(9)))),home:Store.i.current==null?const Login():const Home());}
class Logo extends StatelessWidget{final double h;const Logo({super.key,this.h=60});@override Widget build(BuildContext c)=>Image.asset('assets/images/icone_logo.png',height:h,fit:BoxFit.contain);}
class Avatar extends StatelessWidget{final double r;const Avatar({super.key,this.r=22});@override Widget build(BuildContext c)=>ListenableBuilder(listenable:Store.i,builder:(x,_){final p=Store.i.current?.photo??'';final ok=p.isNotEmpty&&File(p).existsSync();return CircleAvatar(radius:r,backgroundColor:Colors.white,backgroundImage:ok?FileImage(File(p)):null,child:ok?null:Icon(Icons.person,color:green,size:r*1.2));});}
class Bar extends StatelessWidget implements PreferredSizeWidget{final String title;final bool menu;const Bar({super.key,this.title='',this.menu=false});@override Size get preferredSize=>Size.fromHeight(title.isEmpty?100:76);@override Widget build(BuildContext c)=>AppBar(toolbarHeight:title.isEmpty?100:76,centerTitle:true,leading:menu?Builder(builder:(x)=>IconButton(onPressed:()=>Scaffold.of(x).openDrawer(),icon:const Icon(Icons.menu))):null,title:title.isEmpty?Container(width:190,height:88,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(10)),padding:const EdgeInsets.all(4),child:const Logo(h:80)):Text(title,style:const TextStyle(fontWeight:FontWeight.bold)),actions:menu?[IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Profile())),icon:const Avatar(r:26)),const SizedBox(width:8)]:null);}
 
class Login extends StatefulWidget{const Login({super.key});@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final u=TextEditingController(),p=TextEditingController();bool hide=true;@override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF003D2B),Color(0xFF00663D),Color(0xFF001D16)],begin:Alignment.topCenter,end:Alignment.bottomCenter)),child:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:Column(children:[Container(color:Colors.white,padding:const EdgeInsets.all(8),child:const Logo(h:150)),const SizedBox(height:10),const Text('Safe Forest',style:TextStyle(color:Colors.white,fontSize:31,fontWeight:FontWeight.bold)),const Text('G.E.R.S. FLORESTAL',style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold)),const SizedBox(height:25),TextField(controller:u,decoration:const InputDecoration(hintText:'Usuário',prefixIcon:Icon(Icons.person))),const SizedBox(height:10),TextField(controller:p,obscureText:hide,decoration:InputDecoration(hintText:'Senha',prefixIcon:const Icon(Icons.lock),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)))),const SizedBox(height:12),SizedBox(width:double.infinity,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:green,foregroundColor:Colors.white),onPressed:()async{if(await Store.i.login(u.text,p.text)&&c.mounted)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const Home()));else if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Usuário ou senha inválidos.')));},child:const Text('Entrar'))),TextButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const Register())),child:const Text('Criar conta',style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold)))]))))));}
class Register extends StatefulWidget{const Register({super.key});@override State<Register> createState()=>_RegisterState();}
class _RegisterState extends State<Register>{final n=TextEditingController(),u=TextEditingController(),r=TextEditingController(),p=TextEditingController(),p2=TextEditingController();@override Widget build(BuildContext c)=>Scaffold(appBar:const Bar(title:'Criar conta'),body:ListView(padding:const EdgeInsets.all(18),children:[const Logo(h:100),field('Nome completo',n),field('Usuário',u),field('Função',r),field('Senha',p,secret:true),field('Confirmar senha',p2,secret:true),ElevatedButton(onPressed:()async{if(p.text!=p2.text){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('As senhas não conferem.')));return;}final e=await Store.i.register(u.text,p.text,n.text,r.text);if(!c.mounted)return;if(e==null){Navigator.pop(c);ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Conta criada. Faça o login.')));}else ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e)));},child:const Text('Criar usuário'))]));Widget field(String s,TextEditingController x,{bool secret=false})=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:x,obscureText:secret,decoration:InputDecoration(labelText:s)));}
 
Occ fresh(){final d=DateTime.now();String z(int x)=>x.toString().padLeft(2,'0');final o=Occ(d.microsecondsSinceEpoch.toString(),'${z(d.day)}/${z(d.month)}/${d.year}','${z(d.hour)}:${z(d.minute)}');o.employee=Store.i.current?.name??'';o.role=Store.i.current?.role??'';return o;}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{@override void initState(){super.initState();Store.i.addListener(refresh);}@override void dispose(){Store.i.removeListener(refresh);super.dispose();}void refresh(){if(mounted)setState((){});}Widget box(BuildContext c,IconData i,int n,String t,Color col)=>Expanded(child:InkWell(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Occurrences(filter:t))),child:Container(margin:const EdgeInsets.all(4),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:col,borderRadius:BorderRadius.circular(9)),child:Column(children:[Icon(i,color:Colors.white,size:30),Text('$n',style:const TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.bold)),Text(t,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white))]))));@override Widget build(BuildContext c){final a=Store.i.occ;return Scaffold(appBar:const Bar(menu:true),drawer:const Menu(),floatingActionButton:FloatingActionButton(backgroundColor:green,foregroundColor:Colors.white,onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>NewOcc(o:fresh()))),child:const Icon(Icons.add)),body:ListView(padding:const EdgeInsets.all(14),children:[Text('Olá, ${Store.i.current?.name??'Colaborador'}!',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const Text('Segurança sempre em primeiro lugar!'),const SizedBox(height:12),Row(children:[box(c,Icons.list_alt,a.length,'Total de ocorrências',const Color(0xFF00A64F)),box(c,Icons.warning,a.where((x)=>x.status=='Em análise').length,'Em análise',const Color(0xFFF03250))]),Row(children:[box(c,Icons.settings,a.where((x)=>x.status=='Ação corretiva').length,'Ação corretiva',Colors.orange),box(c,Icons.check_circle,a.where((x)=>x.status=='Encerrada').length,'Encerrada',Colors.blue)]),const SizedBox(height:18),const Text('Últimas ocorrências',style:TextStyle(fontSize:21,fontWeight:FontWeight.bold)),if(a.isEmpty)const Padding(padding:EdgeInsets.all(25),child:Center(child:Text('Nenhuma ocorrência registrada.')))else ...a.take(5).map((o)=>Card(child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Details(o:o))),leading:Icon(o.status=='Encerrada'?Icons.check_circle:Icons.warning,color:o.status=='Encerrada'?Colors.green:Colors.red),title:Text(o.type.isEmpty?'Ocorrência':o.type,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${o.date} • ${o.employee}\n${o.status}'),isThreeLine:true,trailing:const Icon(Icons.chevron_right))))]));}}
class Menu extends StatelessWidget{const Menu({super.key});Widget it(BuildContext c,IconData i,String s,Widget p)=>ListTile(leading:Icon(i,color:Colors.white),title:Text(s,style:const TextStyle(color:Colors.white)),onTap:(){Navigator.pop(c);Navigator.push(c,MaterialPageRoute(builder:(_)=>p));});@override Widget build(BuildContext c)=>Drawer(backgroundColor:darkGreen,child:SafeArea(child:Column(children:[Container(color:Colors.white,margin:const EdgeInsets.all(15),padding:const EdgeInsets.all(5),child:const Logo(h:90)),const Text('Safe Forest',style:TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.bold)),const Text('G.E.R.S. FLORESTAL',style:TextStyle(color:Colors.white70)),it(c,Icons.home,'Início',const Home()),it(c,Icons.add,'Nova Ocorrência',NewOcc(o:fresh())),it(c,Icons.list_alt,'Ocorrências',const Occurrences()),it(c,Icons.groups,'Funcionários',const Generic(title:'Funcionários',icon:Icons.groups)),it(c,Icons.agriculture,'Máquinas e Equipamentos',const Generic(title:'Máquinas e Equipamentos',icon:Icons.agriculture)),it(c,Icons.home_work,'Propriedades',const Generic(title:'Propriedades',icon:Icons.home_work)),it(c,Icons.description,'Relatórios',const Reports()),it(c,Icons.settings,'Configurações',const Configuracoes()),const Spacer(),ListTile(leading:const Icon(Icons.logout,color:Colors.white),title:const Text('Sair',style:TextStyle(color:Colors.white)),onTap:()async{await Store.i.logout();if(c.mounted)Navigator.pushAndRemoveUntil(c,MaterialPageRoute(builder:(_)=>const Login()),(_)=>false);})])));}
class Generic extends StatefulWidget{final String title;final IconData icon;const Generic({super.key,required this.title,required this.icon});@override State<Generic> createState()=>_GenericState();}
class _GenericState extends State<Generic>{final items=<String>[];final x=TextEditingController();@override Widget build(BuildContext c)=>Scaffold(appBar:Bar(title:widget.title),floatingActionButton:FloatingActionButton(onPressed:()=>showDialog(context:c,builder:(d)=>AlertDialog(title:Text('Adicionar ${widget.title}'),content:TextField(controller:x,decoration:const InputDecoration(labelText:'Nome / identificação')),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancelar')),ElevatedButton(onPressed:(){if(x.text.trim().isNotEmpty)setState(()=>items.add(x.text.trim()));x.clear();Navigator.pop(d);},child:const Text('Salvar'))])),child:const Icon(Icons.add)),body:items.isEmpty?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(widget.icon,size:65,color:green),Text('Nenhum item em ${widget.title}.')])):ListView(children:items.map((e)=>ListTile(leading:Icon(widget.icon,color:green),title:Text(e),trailing:IconButton(icon:const Icon(Icons.delete),onPressed:()=>setState(()=>items.remove(e))))).toList()));}
 
// ===== Configurações: editar, apagar e resetar relatórios/ocorrências =====
class Configuracoes extends StatefulWidget{const Configuracoes({super.key});@override State<Configuracoes> createState()=>_ConfiguracoesState();}
class _ConfiguracoesState extends State<Configuracoes>{
  Future<bool> confirmar(String t,String m)async{final r=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text(t),content:Text(m),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Colors.red,foregroundColor:Colors.white),onPressed:()=>Navigator.pop(d,true),child:const Text('Confirmar'))]));return r==true;}
  void aviso(String s){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
 
  Future<void> editarRel(Report r)async{
    final t=TextEditingController(text:r.title),x=TextEditingController(text:r.text);
    final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Editar relatório'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Título')),const SizedBox(height:10),TextField(controller:x,maxLines:12,decoration:const InputDecoration(labelText:'Texto do relatório'))])),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),ElevatedButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Salvar'))]));
    if(ok==true){if(t.text.trim().isNotEmpty)r.title=t.text.trim();r.text=x.text;await Store.i.save();if(mounted){setState((){});aviso('Relatório atualizado.');}}
  }
  Future<void> apagarRel(Report r)async{if(await confirmar('Apagar relatório','Deseja apagar "${r.title}"? Esta ação não pode ser desfeita.')){Store.i.reports.remove(r);await Store.i.save();if(mounted)setState((){});}}
  Future<void> resetRel()async{if(await confirmar('Resetar relatórios','Todos os relatórios salvos serão apagados de uma só vez. Deseja continuar?')){Store.i.reports.clear();await Store.i.save();if(mounted){setState((){});aviso('Todos os relatórios foram apagados.');}}}
 
  Future<void> editarOcc(Occ o)async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>NewOcc(o:Occ.from(o.json()),edit:true)));if(mounted)setState((){});}
  Future<void> apagarOcc(Occ o)async{if(await confirmar('Apagar ocorrência','Deseja apagar esta ocorrência (${o.date} - ${o.type.isEmpty?'Ocorrência':o.type})? Esta ação não pode ser desfeita.')){Store.i.occ.removeWhere((x)=>x.id==o.id);await Store.i.save();if(mounted)setState((){});}}
  Future<void> resetOcc()async{if(await confirmar('Resetar ocorrências','Todas as ocorrências serão apagadas de uma só vez e os contadores do início voltam a zero. Deseja continuar?')){Store.i.occ.clear();await Store.i.save();if(mounted){setState((){});aviso('Todas as ocorrências foram apagadas.');}}}
 
  Widget acoes(VoidCallback editar,VoidCallback apagar)=>Row(mainAxisSize:MainAxisSize.min,children:[IconButton(tooltip:'Editar',icon:const Icon(Icons.edit),onPressed:editar),IconButton(tooltip:'Apagar',icon:const Icon(Icons.delete,color:Colors.red),onPressed:apagar)]);
  Widget rodape(String label,bool vazio,VoidCallback f)=>SafeArea(child:Padding(padding:const EdgeInsets.all(12),child:SizedBox(width:double.infinity,child:OutlinedButton.icon(style:OutlinedButton.styleFrom(foregroundColor:Colors.red,side:const BorderSide(color:Colors.red),padding:const EdgeInsets.symmetric(vertical:14)),icon:const Icon(Icons.delete_forever),label:Text(label),onPressed:vazio?null:f))));
 
  Widget tabRel(){final l=Store.i.reports;return Column(children:[Expanded(child:l.isEmpty?const Center(child:Text('Nenhum relatório salvo.')):ListView(padding:const EdgeInsets.all(8),children:l.map((r)=>Card(child:ListTile(leading:const Icon(Icons.description,color:green),title:Text(r.title),trailing:acoes(()=>editarRel(r),()=>apagarRel(r))))).toList())),rodape('Resetar relatórios (apagar todos)',l.isEmpty,resetRel)]);}
  Widget tabOcc(){final l=Store.i.occ;return Column(children:[Expanded(child:l.isEmpty?const Center(child:Text('Nenhuma ocorrência registrada.')):ListView(padding:const EdgeInsets.all(8),children:l.map((o)=>Card(child:ListTile(leading:const Icon(Icons.report,color:green),title:Text(o.type.isEmpty?'Ocorrência':o.type),subtitle:Text('${o.date} • ${o.employee}\n${o.farm}'),isThreeLine:true,trailing:acoes(()=>editarOcc(o),()=>apagarOcc(o))))).toList())),rodape('Resetar ocorrências (apagar todas)',l.isEmpty,resetOcc)]);}
 
  @override Widget build(BuildContext c)=>DefaultTabController(length:2,child:Scaffold(appBar:const Bar(title:'Configurações'),body:Column(children:[const Material(color:Colors.white,child:TabBar(labelColor:darkGreen,indicatorColor:green,tabs:[Tab(icon:Icon(Icons.description),text:'Relatórios'),Tab(icon:Icon(Icons.list_alt),text:'Ocorrências')])),Expanded(child:TabBarView(children:[tabRel(),tabOcc()]))])));
}
 
class Profile extends StatefulWidget{const Profile({super.key});@override State<Profile> createState()=>_ProfileState();}
class _ProfileState extends State<Profile>{Future<void> pick(ImageSource s)async{final f=await ImagePicker().pickImage(source:s,imageQuality:80);if(f!=null){final d=await getApplicationDocumentsDirectory();final n='${d.path}/perfil_${DateTime.now().millisecondsSinceEpoch}.jpg';await File(f.path).copy(n);Store.i.current!.photo=n;await Store.i.save();if(mounted)setState((){});}}@override Widget build(BuildContext c){final u=Store.i.current!;return Scaffold(appBar:const Bar(title:'Meu Perfil'),body:ListView(padding:const EdgeInsets.all(20),children:[const Center(child:Avatar(r:60)),Center(child:Text(u.name,style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold))),Center(child:Text(u.role)),const SizedBox(height:18),ElevatedButton.icon(onPressed:()=>pick(ImageSource.camera),icon:const Icon(Icons.camera_alt),label:const Text('Adicionar/Trocar pela câmera')),ElevatedButton.icon(onPressed:()=>pick(ImageSource.gallery),icon:const Icon(Icons.photo_library),label:const Text('Adicionar/Trocar pela galeria')),OutlinedButton.icon(onPressed:()async{u.photo='';await Store.i.save();setState((){});},icon:const Icon(Icons.delete),label:const Text('Excluir foto'))]));}}
 
class Dots extends StatelessWidget{final int step;const Dots(this.step,{super.key});@override Widget build(BuildContext c)=>Row(children:List.generate(5,(i)=>Expanded(child:Row(children:[Expanded(child:Container(height:4,color:i<=step?green:Colors.grey.shade300)),CircleAvatar(radius:7,backgroundColor:i<=step?green:Colors.grey.shade300)]))));}
class NewOcc extends StatefulWidget{final Occ o;final bool edit;const NewOcc({super.key,required this.o,this.edit=false});@override State<NewOcc> createState()=>_NewOccState();}
class _NewOccState extends State<NewOcc>{int step=0;final farm=TextEditingController(),plot=TextEditingController(),op=TextEditingController(),desc=TextEditingController(),hospital=TextEditingController(),emp=TextEditingController(),rol=TextEditingController();@override void initState(){super.initState();farm.text=widget.o.farm;plot.text=widget.o.plot;op.text=widget.o.operation;desc.text=widget.o.desc;hospital.text=widget.o.hospital;emp.text=widget.o.employee;rol.text=widget.o.role;}void sync(){widget.o.farm=farm.text;widget.o.plot=plot.text;widget.o.operation=op.text;widget.o.desc=desc.text;widget.o.hospital=hospital.text;widget.o.employee=emp.text.trim();widget.o.role=rol.text.trim();}Widget inp(String s,TextEditingController c)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,maxLines:s.startsWith('Descrição')?4:1,decoration:InputDecoration(labelText:s)));
Future<void> gps()async{if(!await Geolocator.isLocationServiceEnabled())return;var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();if(p==LocationPermission.denied||p==LocationPermission.deniedForever)return;final z=await Geolocator.getCurrentPosition(desiredAccuracy:LocationAccuracy.high);if(mounted)setState((){widget.o.lat=z.latitude;widget.o.lng=z.longitude;widget.o.accuracy=z.accuracy;});}
Future<void> photo()async{final f=await ImagePicker().pickImage(source:ImageSource.camera,imageQuality:75);if(f!=null)setState(()=>widget.o.photos.add(f.path));}
Widget accident(String s,IconData i){final on=widget.o.type==s;return InkWell(onTap:()=>setState(()=>widget.o.type=s),child:Container(decoration:BoxDecoration(color:on?paleGreen:Colors.grey.shade100,border:Border.all(color:on?green:Colors.grey.shade300),borderRadius:BorderRadius.circular(9)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(i,color:on?green:Colors.red,size:29),Text(s,textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold))])));}
Widget check(String s,List<String> l)=>CheckboxListTile(contentPadding:EdgeInsets.zero,dense:true,value:l.contains(s),title:Text(s),onChanged:(v)=>setState((){if(v==true){if(!l.contains(s))l.add(s);}else l.remove(s);}));
Future<void> finalizar(BuildContext c)async{
  await ColabStore.add(emp.text);
  if(widget.edit){
    final i=Store.i.occ.indexWhere((x)=>x.id==widget.o.id);
    if(i>=0)Store.i.occ[i]=widget.o;
    await Store.i.save();
    if(c.mounted){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Ocorrência atualizada.')));Navigator.pop(c);}
  }else{
    Store.i.occ.insert(0,widget.o);
    await Store.i.save();
    if(c.mounted)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>ReportPage(o:widget.o)));
  }
}
@override Widget build(BuildContext c){final titles=['1. Dados Gerais','2. Detalhes','3. Fotos e Localização','4. Atendimento e Causas','5. Revisão'];return Scaffold(appBar:Bar(title:widget.edit?'Editar Ocorrência':'Nova Ocorrência'),body:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(18,18,18,5),child:Dots(step)),Text(titles[step],style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),Expanded(child:SingleChildScrollView(padding:const EdgeInsets.all(16),child:[general(),details(),photos(),causes(),review()][step])),Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:OutlinedButton(onPressed:(){if(step==0)Navigator.pop(c);else setState(()=>step--);},child:const Text('Voltar'))),const SizedBox(width:8),Expanded(child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:green,foregroundColor:Colors.white),onPressed:()async{sync();if(step<4)setState(()=>step++);else await finalizar(c);},child:Text(step==4?(widget.edit?'Salvar alterações':'Salvar ocorrência'):'Próximo')))]))]));}
Widget general()=>Column(children:[inp('Local / Fazenda *',farm),inp('Talhão / Talhonamento',plot),CampoColab(controller:emp),inp('Função',rol),inp('Operação realizada *',op)]);
Widget details()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Tipo de acidente *',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),GridView.count(crossAxisCount:3,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),mainAxisSpacing:7,crossAxisSpacing:7,children:[accident('Queda',Icons.directions_run),accident('Corte',Icons.content_cut),accident('Atropelamento',Icons.directions_car),accident('Prensagem',Icons.local_shipping),accident('Choque',Icons.flash_on),accident('Picada de animais',Icons.pets),accident('Outro',Icons.more_horiz)]),if(widget.o.type=='Picada de animais')...[const SizedBox(height:10),DropdownButtonFormField<String>(value:widget.o.animal.isEmpty?null:(widget.o.animal=='Inseto'||widget.o.animal=='Outro'?'Inseto / Outro':widget.o.animal),decoration:const InputDecoration(labelText:'Animal envolvido'),items:['Serpente','Aranha','Escorpião','Abelha','Inseto / Outro'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>widget.o.animal=v??'')],const SizedBox(height:12),inp('Descrição do acidente *',desc),const Text('Parte do corpo atingida *',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:7,children:['Cabeça','Tronco','Braço','Mão','Perna','Pé','Outra parte'].map((e)=>ChoiceChip(label:Text(e),selected:widget.o.body==e,onSelected:(_)=>setState(()=>widget.o.body=e))).toList())]);
Widget photos()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Fotos do local e do acidente',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:8,runSpacing:8,children:[InkWell(onTap:photo,child:Container(width:120,height:120,decoration:BoxDecoration(border:Border.all(color:Colors.grey)),child:const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.camera_alt,color:green,size:35),Text('Adicionar foto')]))),...widget.o.photos.map((p)=>Stack(children:[Image.file(File(p),width:120,height:120,fit:BoxFit.cover),Positioned(right:0,child:IconButton(onPressed:()=>setState(()=>widget.o.photos.remove(p)),icon:const Icon(Icons.close,color:Colors.red)))]) )]),const SizedBox(height:18),const Text('Localização (GPS)',style:TextStyle(fontWeight:FontWeight.bold)),Container(height:150,width:double.infinity,color:const Color(0xFF315F45),child:const Icon(Icons.location_pin,color:Colors.red,size:60)),SizedBox(width:double.infinity,child:ElevatedButton.icon(onPressed:gps,icon:const Icon(Icons.my_location),label:const Text('Atualizar localização em tempo real'))),Row(children:[Expanded(child:TextFormField(key:ValueKey(widget.o.lat),readOnly:true,initialValue:widget.o.lat==0?'—':widget.o.lat.toStringAsFixed(7),decoration:const InputDecoration(labelText:'Latitude'))),const SizedBox(width:8),Expanded(child:TextFormField(key:ValueKey(widget.o.lng),readOnly:true,initialValue:widget.o.lng==0?'—':widget.o.lng.toStringAsFixed(7),decoration:const InputDecoration(labelText:'Longitude')))]),if(widget.o.accuracy>0)Text('Precisão: ${widget.o.accuracy.toStringAsFixed(1)} m')]);
Widget causes()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Atendimento realizado *',style:TextStyle(fontWeight:FontWeight.bold)),...['Primeiros socorros no local','Encaminhado ao hospital','Atendimento médico na empresa','Não houve atendimento'].map((e)=>check(e,widget.o.attendance)),inp('Unidade de atendimento',hospital),const Text('Possíveis causas *',style:TextStyle(fontWeight:FontWeight.bold)),...['Falha operacional','Falta de EPI','Condição insegura','Fator humano','Falha de equipamento','Outra'].map((e)=>check(e,widget.o.causes))]);
Widget rr(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:115,child:Text(a,style:const TextStyle(color:Colors.black54))),Expanded(child:Text(b))]));
Widget review()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Resumo da Ocorrência',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),rr('Data/Hora','${widget.o.date} - ${widget.o.time}'),rr('Local','${widget.o.farm} - ${widget.o.plot}'),rr('Funcionário',widget.o.employee),rr('Função',widget.o.role),rr('Operação',widget.o.operation),rr('Tipo',widget.o.type),if(widget.o.animal.isNotEmpty)rr('Animal',widget.o.animal),rr('Parte atingida',widget.o.body),rr('Descrição',widget.o.desc),rr('GPS',widget.o.lat==0?'Não capturado':'${widget.o.lat.toStringAsFixed(7)}, ${widget.o.lng.toStringAsFixed(7)}')]);}
 
String report(Occ o)=>'''SAFE FOREST - G.E.R.S. FLORESTAL
RELATÓRIO DE OCORRÊNCIA
 
Data/Hora: ${o.date} - ${o.time}
Local: ${o.farm} - ${o.plot}
Empresa: G.E.R.S. FLORESTAL
Funcionário: ${o.employee}
Função: ${o.role}
Operação: ${o.operation}
Tipo de acidente: ${o.type}
${o.animal.isNotEmpty?'Animal envolvido: ${o.animal}\n':''}Parte atingida: ${o.body}
Descrição: ${o.desc}
Atendimento: ${o.attendance.join(', ')}
Unidade: ${o.hospital}
Possíveis causas: ${o.causes.join(', ')}
Latitude: ${o.lat}
Longitude: ${o.lng}
Precisão GPS: ${o.accuracy.toStringAsFixed(1)} m
Status: ${o.status}
''';
class ReportPage extends StatelessWidget{final Occ o;const ReportPage({super.key,required this.o});Future<void> save(BuildContext c)async{final t=report(o);Store.i.reports.insert(0,Report(DateTime.now().microsecondsSinceEpoch.toString(),'${o.date} - ${o.type}',t));await Store.i.save();final d=await getApplicationDocumentsDirectory();await File('${d.path}/relatorio_${o.id}.txt').writeAsString(t);if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Relatório salvo dentro do aplicativo.')));}Future<void> share()async=>SharePlus.instance.share(ShareParams(text:report(o),subject:'Relatório Safe Forest - ${o.date}'));@override Widget build(BuildContext c)=>Scaffold(appBar:const Bar(title:'Relatório de Ocorrência'),body:ListView(padding:const EdgeInsets.all(16),children:[const Logo(h:90),const Center(child:Text('G.E.R.S. FLORESTAL',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18))),const Divider(),SelectableText(report(o),style:const TextStyle(fontSize:16,height:1.45)),Row(children:[Expanded(child:ElevatedButton.icon(onPressed:share,icon:const Icon(Icons.share),label:const Text('Compartilhar'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:()=>save(c),icon:const Icon(Icons.save),label:const Text('Salvar')))])]));}
class Details extends StatefulWidget{final Occ o;const Details({super.key,required this.o});@override State<Details> createState()=>_DetailsState();}
class _DetailsState extends State<Details>{@override Widget build(BuildContext c){final o=widget.o;return Scaffold(appBar:const Bar(title:'Detalhes da Ocorrência'),body:ListView(padding:const EdgeInsets.all(16),children:[const Logo(h:80),SelectableText(report(o)),const SizedBox(height:12),DropdownButtonFormField<String>(value:o.status,decoration:const InputDecoration(labelText:'Status'),items:['Em análise','Ação corretiva','Encerrada'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)async{if(v!=null){o.status=v;await Store.i.save();setState((){});}}),ElevatedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ReportPage(o:o))),icon:const Icon(Icons.description),label:const Text('Abrir relatório'))]));}}
class Occurrences extends StatelessWidget{final String? filter;const Occurrences({super.key,this.filter});@override Widget build(BuildContext c){var a=Store.i.occ;if(filter!=null&&filter!='Total de ocorrências')a=a.where((x)=>x.status==filter).toList();return Scaffold(appBar:const Bar(title:'Ocorrências'),body:a.isEmpty?const Center(child:Text('Nenhuma ocorrência encontrada.')):ListView(children:a.map((o)=>Card(child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Details(o:o))),leading:const Icon(Icons.report,color:green),title:Text(o.type.isEmpty?'Ocorrência':o.type),subtitle:Text('${o.date} • ${o.employee}\n${o.status}'),isThreeLine:true,trailing:const Icon(Icons.chevron_right)))).toList()));}}
class Reports extends StatefulWidget{const Reports({super.key});@override State<Reports> createState()=>_ReportsState();}
class _ReportsState extends State<Reports>{@override Widget build(BuildContext c)=>Scaffold(appBar:const Bar(title:'Relatórios'),body:Store.i.reports.isEmpty?const Center(child:Text('Nenhum relatório salvo.')):ListView(children:Store.i.reports.map((r)=>ListTile(leading:const Icon(Icons.description,color:green),title:Text(r.title),onTap:()=>showDialog(context:c,builder:(d)=>AlertDialog(title:Text(r.title),content:SingleChildScrollView(child:SelectableText(r.text)),actions:[TextButton(onPressed:()=>SharePlus.instance.share(ShareParams(text:r.text,subject:r.title)),child:const Text('Compartilhar')),TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Fechar'))])))).toList()));}
 
